all: INT01 INT17 INT18 MEM00

INT01: INT01.c
	gcc -g -Wall -o INT01 INT01.c

INT17: INT17.c
	gcc -g -Wall -o INT17 INT17.c

INT18: INT18.c
	gcc -g -Wall -o INT18 INT18.c

MEM00: MEM00.c
	gcc -g -Wall -o MEM00 MEM00.c

clean:
	rm INT01 INT17 INT18 MEM00