all: INT30 INT31 ENV32 ENV33 ARR38

INT30: INT30.c
	gcc -g -Wall -o INT30 INT30.c

INT31: INT31.c
	gcc -g -Wall -o INT31 INT31.c

ENV32: ENV32.c
	gcc -g -Wall -o ENV32 ENV32.c

ENV33: ENV33.c
	gcc -g -Wall -o ENV33 ENV33.c

ARR38: ARR38.c
	gcc -g -Wall -o ARR38 ARR38.c
clean:
	rm -f INT30 INT31 ENV32 ENV33 ARR38